# Generated by Django 4.1 on 2022-12-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_code', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
