# Generated by Django 4.1 on 2022-12-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_code', '0002_remove_products_id_alter_products_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
